name: RepairBillBinder
options:
  bundleIdPrefix: com.shimondeitel.repairbinder
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  RepairBillBinder:
    type: application
    platform: iOS
    sources:
      - path: RepairBillBinder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.repairbinder
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: RepairBillBinder/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  RepairBillBinderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RepairBillBinderTests
      - path: RepairBillBinder.storekit
    dependencies:
      - target: RepairBillBinder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.repairbinder.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  RepairBillBinderUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: RepairBillBinderUITests
    dependencies:
      - target: RepairBillBinder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.repairbinder.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  RepairBillBinder:
    build:
      targets:
        RepairBillBinder: all
        RepairBillBinderTests: [test]
        RepairBillBinderUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: RepairBillBinder.storekit
    test:
      config: Debug
      storeKitConfiguration: RepairBillBinder.storekit
      targets:
        - RepairBillBinderTests
        - RepairBillBinderUITests
    archive:
      config: Release
